version: '3.11'
services:

  chadbot-app:
    build: ./
    container_name: chadbot-app
    ports:
      - 7860:7860
    links:
      - chadbot-db

  chadbot-db:
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=chad-boys

